= Define the constraints and calculate the score
:imagesdir: ../..

A _score_ represents the quality of a specific solution.
The higher the better.
Timefold Solver looks for the best solution, which is the solution with the highest score found in the available time.
It might be the _optimal_ solution.

Because this use case has hard and soft constraints,
use the `HardSoftScore` class to represent the score:

* Hard constraints must not be broken.
For example: _A room can have at most one lesson at the same time._
* Soft constraints should not be broken.
For example: _A teacher prefers to teach in a single room._

Hard constraints are weighted against other hard constraints.
Soft constraints are weighted too, against other soft constraints.
*Hard constraints always outweigh soft constraints*, regardless of their respective weights.

To calculate the score, you could implement an `EasyScoreCalculator` class:

[tabs]
====
Python::
+
--

[source,python]
----
from timefold.score.score import easy_score_calculator, HardSoftScore

@easy_score_calculator
def school_timetable_constraints(solution: Timetable):
    lessons = solution.lessons
    hard_score = 0
    for a in lessons:
        for b in lessons:
            if a.timeslot != null and a.timeslot == b.timeslot and a.id < b.id:
                # A room can accommodate at most one lesson at the same time.
                if a.room != null and a.room == b.room:
                    hard_score -= 1

                # A teacher can teach at most one lesson at the same time.
                if a.teacher == b.teacher:
                    hard_score -= 1

                # A student can attend at most one lesson at the same time.
                if a.student_group == b.student_group:
                    hard_score -= 1
    soft_score = 0
    # Soft constraints are only implemented in the timefold-quickstarts code
    return HardSoftScore.of(hard_score, soft_score)
----
--
====


Unfortunately **that does not scale well**, because it is non-incremental:
every time a lesson is assigned to a different time slot or room,
all lessons are re-evaluated to calculate the new score.

Instead, create a `TimetableConstraintProvider` class
to perform incremental score calculation.
It uses Timefold Solver's xref:constraints-and-score/score-calculation.adoc[Constraint Streams API]
which is inspired by SQL:

[tabs]
====
Python::
+
--
Create a `school_timetabling_constraints` function in `src/hello_world/constraints.py`:

[source,python]
----
from timefold.solver.score import (constraint_provider, HardSoftScore, Joiners,
                                   ConstraintFactory, Constraint)
from .domain import Lesson

@constraint_provider
def define_constraints(constraint_factory: ConstraintFactory):
    return [
        room_conflict(constraint_factory),
        teacher_conflict(constraint_factory),
        student_group_conflict(constraint_factory),

        # Soft constraints are only implemented in the timefold-quickstarts code
    ]


def room_conflict(constraint_factory: ConstraintFactory) -> Constraint:
    # A room can accommodate at most one lesson at the same time.
    return (constraint_factory
            # Select each pair of 2 different lessons ...
            .for_each_unique_pair(Lesson,
                                  # ... in the same timeslot ...
                                  Joiners.equal(lambda lesson: lesson.timeslot),
                                  # ... in the same room ...
                                  Joiners.equal(lambda lesson: lesson.room))
            # ... and penalize each pair with a hard weight.
            .penalize(HardSoftScore.ONE_HARD)
            .as_constraint("Room conflict"))


def teacher_conflict(constraint_factory: ConstraintFactory) -> Constraint:
    # A teacher can teach at most one lesson at the same time.
    return (constraint_factory
            .for_each_unique_pair(Lesson,
                                  Joiners.equal(lambda lesson: lesson.timeslot),
                                  Joiners.equal(lambda lesson: lesson.teacher))
            .penalize(HardSoftScore.ONE_HARD)
            .as_constraint("Teacher conflict"))


def student_group_conflict(constraint_factory: ConstraintFactory) -> Constraint:
    # A student can attend at most one lesson at the same time.
    return (constraint_factory
            .for_each_unique_pair(Lesson,
                                  Joiners.equal(lambda lesson: lesson.timeslot),
                                  Joiners.equal(lambda lesson: lesson.student_group))
            .penalize(HardSoftScore.ONE_HARD)
            .as_constraint("Student group conflict"))
----
--
====

The `ConstraintProvider` scales an order of magnitude better than the `EasyScoreCalculator`: __O__(n) instead of __O__(n²).
