[#helloWorldQuickStart]
= Hello World Quick Start Guide
:doctype: book
:imagesdir: ../..
:sectnums:
:icons: font
include::../../_attributes.adoc[]

This guide walks you through the process of creating a simple Python application
with https://timefold.ai[Timefold]'s constraint solving Artificial Intelligence (AI).

== What you will build

You will build a command-line application that optimizes a school timetable for students and teachers:

----
...
INFO  Solving ended: time spent (5000), best score (0hard/9soft), ...
INFO
INFO  |            | Room A     | Room B     | Room C     |
INFO  |------------|------------|------------|------------|
INFO  | MON 08:30  | English    | Math       |            |
INFO  |            | I. Jones   | A. Turing  |            |
INFO  |            | 9th grade  | 10th grade |            |
INFO  |------------|------------|------------|------------|
INFO  | MON 09:30  | History    | Physics    |            |
INFO  |            | I. Jones   | M. Curie   |            |
INFO  |            | 9th grade  | 10th grade |            |
INFO  |------------|------------|------------|------------|
INFO  | MON 10:30  | History    | Physics    |            |
INFO  |            | I. Jones   | M. Curie   |            |
INFO  |            | 10th grade | 9th grade  |            |
INFO  |------------|------------|------------|------------|
...
INFO  |------------|------------|------------|------------|
----

Your application will assign `Lesson` instances to `Timeslot` and `Room` instances automatically
by using AI to adhere to hard and soft scheduling _constraints_, for example:

* A room can have at most one lesson at the same time.
* A teacher can teach at most one lesson at the same time.
* A student can attend at most one lesson at the same time.
* A teacher prefers to teach all lessons in the same room.
* A teacher prefers to teach sequential lessons and dislikes gaps between lessons.
* A student dislikes sequential lessons on the same subject.

Mathematically speaking, school timetabling is an _NP-hard_ problem.
This means it is difficult to scale.
Simply brute force iterating through all possible combinations takes millions of years
for a non-trivial dataset, even on a supercomputer.
Fortunately, AI constraint solvers such as Timefold Solver have advanced algorithms
that deliver a near-optimal solution in a reasonable amount of time.

== Solution source code

Follow the instructions in the next sections to create the application step by step (recommended).

Alternatively, review the completed example:

. Complete one of the following tasks:
.. Clone the Git repository:
+
[source,shell,subs=attributes+]
----
$ git clone {quickstarts-clone-url}
----

. Find the solution in
+
[tabs]
====
Python::
{hello-world-python-quickstart-url}[the `python` directory].
====

. Follow the instructions in the README file to run the application.

== Prerequisites

To complete this guide, you need:

[tabs]
====
Python::
+
--
* https://adoptopenjdk.net/[JDK] {java-version}+ with `JAVA_HOME` configured appropriately
* https://www.python.org/downloads/[Python] {python-version}+
* An IDE, such as https://www.jetbrains.com/pycharm/[IntelliJ PyCharm] or https://code.visualstudio.com[VSCode]
--
====

== The build file and the dependencies

Create a `pyproject.toml` build file and add these dependencies:

* `timefold` to solve the school timetable problem.
* `pytest` to test the school timetabling constraints.

[tabs]
====
Python::
+
--
Your `pyproject.toml` file has this content:

[source,toml,subs=attributes+]
----
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "hello_world"
version = "1.0.0"
requires-python = ">= {python-version}"
dependencies = [
    "timefold == {timefold-solver-python-version}",
    "pytest == 8.2.2"
]


----
--
====

include::../shared/school-timetabling/school-timetabling-model.adoc[leveloffset=+1]
include::../shared/school-timetabling/school-timetabling-constraints.adoc[leveloffset=+1]
include::../shared/school-timetabling/school-timetabling-solution.adoc[leveloffset=+1]

== Create the application

Now you are ready to put everything together and create a Java application.
The `main()` method performs the following tasks:

. Creates the `SolverFactory` to build a `Solver` per dataset.
. Loads a dataset.
. Solves it with `Solver.solve()`.
. Visualizes the solution for that dataset.

Typically, an application has a single `SolverFactory`
to build a new `Solver` instance for each problem dataset to solve.
A `SolverFactory` is thread-safe, but a `Solver` is not.
In this case, there is only one dataset, so only one `Solver` instance.

[tabs]
====
Python::
+
--
Create `src/hello_world/main.py` with the following contents:

[source,python]
----
from timefold.solver.config import (SolverConfig, ScoreDirectorFactoryConfig,
                                    TerminationConfig, Duration)
from timefold.solver import SolverFactory
from datetime import time
import logging
import logging.config

from .domain import *
from .constraints import define_constraints

logging.config.fileConfig('logging.conf')
LOGGER = logging.getLogger('app')

def main():
    solver_factory = SolverFactory.create(
        SolverConfig(
            solution_class=Timetable,
            entity_class_list=[Lesson],
            score_director_factory_config=ScoreDirectorFactoryConfig(
                constraint_provider_function=define_constraints
            ),
            termination_config=TerminationConfig(
                # The solver runs only for 5 seconds on this small dataset.
                # It's recommended to run for at least 5 minutes ("5m") otherwise.
                spent_limit=Duration(seconds=5)
            )
        ))

    # Load the problem
    problem = generate_demo_data()

    # Solve the problem
    solver = solver_factory.build_solver()
    solution = solver.solve(problem)

    # Visualize the solution
    print_timetable(solution)


def generate_demo_data() -> Timetable:
    days = ('MONDAY', 'TUESDAY')
    timeslots = [
        Timeslot(day, start, start.replace(hour=start.hour + 1))
        for day in days
        for start in (time(8, 30), time(9, 30), time(10, 30), time(13, 30), time(14, 30))
    ]

    room_ids = ('A', 'B', 'C')
    rooms = [Room(f'Room {name}') for name in room_ids]

    lessons = []

    def id_generator():
        current = 0
        while True:
            yield str(current)
            current += 1

    ids = id_generator()
    lessons.append(Lesson(next(ids), "Math", "A. Turing", "9th grade"))
    lessons.append(Lesson(next(ids), "Math", "A. Turing", "9th grade"))
    lessons.append(Lesson(next(ids), "Physics", "M. Curie", "9th grade"))
    lessons.append(Lesson(next(ids), "Chemistry", "M. Curie", "9th grade"))
    lessons.append(Lesson(next(ids), "Biology", "C. Darwin", "9th grade"))
    lessons.append(Lesson(next(ids), "History", "I. Jones", "9th grade"))
    lessons.append(Lesson(next(ids), "English", "I. Jones", "9th grade"))
    lessons.append(Lesson(next(ids), "English", "I. Jones", "9th grade"))
    lessons.append(Lesson(next(ids), "Spanish", "P. Cruz", "9th grade"))
    lessons.append(Lesson(next(ids), "Spanish", "P. Cruz", "9th grade"))

    lessons.append(Lesson(next(ids), "Math", "A. Turing", "10th grade"))
    lessons.append(Lesson(next(ids), "Math", "A. Turing", "10th grade"))
    lessons.append(Lesson(next(ids), "Math", "A. Turing", "10th grade"))
    lessons.append(Lesson(next(ids), "Physics", "M. Curie", "10th grade"))
    lessons.append(Lesson(next(ids), "Chemistry", "M. Curie", "10th grade"))
    lessons.append(Lesson(next(ids), "French", "M. Curie", "10th grade"))
    lessons.append(Lesson(next(ids), "Geography", "C. Darwin", "10th grade"))
    lessons.append(Lesson(next(ids), "History", "I. Jones", "10th grade"))
    lessons.append(Lesson(next(ids), "English", "P. Cruz", "10th grade"))
    lessons.append(Lesson(next(ids), "Spanish", "P. Cruz", "10th grade"))

    return Timetable("DEMO_DATA", timeslots, rooms, lessons)


def print_timetable(time_table: Timetable) -> None:
    LOGGER.info("")

    column_width = 18
    rooms = time_table.rooms
    timeslots = time_table.timeslots
    lessons = time_table.lessons
    lesson_map = {
        (lesson.room.name, lesson.timeslot.day_of_week, lesson.timeslot.start_time): lesson
        for lesson in lessons
        if lesson.room is not None and lesson.timeslot is not None
    }
    row_format = ("|{:<" + str(column_width) + "}") * (len(rooms) + 1) + "|"
    sep_format = "+" + ((("-" * column_width) + "+") * (len(rooms) + 1))

    LOGGER.info(sep_format)
    LOGGER.info(row_format.format('', *[room.name for room in rooms]))
    LOGGER.info(sep_format)

    for timeslot in timeslots:
        def get_row_lessons():
            for room in rooms:
                yield lesson_map.get((room.name, timeslot.day_of_week, timeslot.start_time),
                                     Lesson('', '', '', ''))

        row_lessons = [*get_row_lessons()]
        LOGGER.info(row_format.format(str(timeslot), *[lesson.subject for lesson in row_lessons]))
        LOGGER.info(row_format.format('', *[lesson.teacher for lesson in row_lessons]))
        LOGGER.info(row_format.format('', *[lesson.student_group for lesson in row_lessons]))
        LOGGER.info(sep_format)

    unassigned_lessons = [lesson for lesson in lessons if lesson.room is None or lesson.timeslot is None]
    if len(unassigned_lessons) > 0:
        LOGGER.info("")
        LOGGER.info("Unassigned lessons")
        for lesson in unassigned_lessons:
            LOGGER.info(f'    {lesson.subject} - {lesson.teacher} - {lesson.student_group}')


if __name__ == '__main__':
    main()
----
--
====

The `main()` method first creates the `SolverFactory`:

[tabs]
====


Python::
+
--
[source,python]
----
solver_factory = SolverFactory.create(
    SolverConfig(
        solution_class=Timetable,
        entity_class_list=[Lesson],
        score_director_factory_config=ScoreDirectorFactoryConfig(
            constraint_provider_function=define_constraints
        ),
        termination_config=TerminationConfig(
            # The solver runs only for 5 seconds on this small dataset.
            # It's recommended to run for at least 5 minutes ("5m") otherwise.
            spent_limit=Duration(seconds=5)
        )
    ))
----
--
====

This registers the `@planning_solution` class, the `@planning_entity` classes,
and the `ConstraintProvider` class, all of which you created earlier.

Without a termination setting or a `terminationEarly()` event, the solver runs forever.
To avoid that, the solver limits the solving time to five seconds.

The `main()` method loads the problem, solves it, and prints the solution after just over five seconds.

[tabs]
====


Python::
+
--
[source,python]
----
# Load the problem
problem = generate_demo_data(DemoData.SMALL)

# Solve the problem
solver = solver_factory.build_solver()
solution = solver.solve(problem)

# Visualize the solution
print_timetable(solution)
----
--
====

The `solve()` method doesn't return instantly.
It runs for five seconds before returning the best solution.

Timefold Solver returns _the best solution_ found in the available termination time.
Due to xref:optimization-algorithms/overview.adoc#doesTimefoldFindTheOptimalSolution[the nature of NP-hard problems],
the best solution might not be optimal, especially for larger datasets.
Increase the termination time to potentially find a better solution.

The `generateDemoData()` method generates the school timetable problem to solve.

The `printTimetable()` method pretty prints the timetable to the console,
allowing to determine visually whether it's a good schedule.

=== Configure logging

To see any output in the console, logging must be configured properly.

[tabs]
====
Python::
+
--
Create the `logging.conf` file:

[source,text]
----
[loggers]
keys=root,timefold_solver

[handlers]
keys=consoleHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=INFO
handlers=consoleHandler

[logger_timefold_solver]
level=INFO
qualname=timefold.solver
handlers=consoleHandler
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=simpleFormatter
args=(sys.stdout,)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
----
--
====

== Run the application

=== Run the application in IDE

[tabs]
====
Python:: Run `src/hello_world/main.py`:
====

----
...
INFO  |            | Room A     | Room B     | Room C     |
INFO  |------------|------------|------------|------------|
INFO  | MON 08:30  | English    | Math       |            |
INFO  |            | I. Jones   | A. Turing  |            |
INFO  |            | 9th grade  | 10th grade |            |
INFO  |------------|------------|------------|------------|
INFO  | MON 09:30  | History    | Physics    |            |
INFO  |            | I. Jones   | M. Curie   |            |
INFO  |            | 9th grade  | 10th grade |            |
...
----

Verify the console output. Does it conform to all hard constraints?
What happens if you comment out the `roomConflict` constraint in `TimetableConstraintProvider`?

The `info` log shows what Timefold Solver did in those five seconds:

[source,options="nowrap"]
----
... Solving started: time spent (33), best score (0hard/0soft), environment mode (PHASE_ASSERT), random (JDK with seed 0).
... Construction Heuristic phase (0) ended: time spent (73), best score (0hard/0soft), move evaluation speed (459/sec), step total (4).
... Local Search phase (1) ended: time spent (5000), best score (0hard/0soft), move evaluation speed (28949/sec), step total (28398).
... Solving ended: time spent (5000), best score (0hard/0soft), move evaluation speed (28524/sec), phase total (2), environment mode (PHASE_ASSERT).
----

=== Test the application

A good application includes test coverage.

==== Test the constraints

To test each constraint in isolation, use a `ConstraintVerifier` in unit tests.
This tests each constraint's corner cases in isolation from the other tests,
which lowers maintenance when adding a new constraint with proper test coverage.


[tabs]
====


Python::
+
--
Create the `tests/test_constraints.py` file with the following contents:

[source,python]
----
from timefold.solver.test import ConstraintVerifier
from datetime import time

from hello_world.domain import *
from hello_world.constraints import *

ROOM1 = Room("Room1")
ROOM2 = Room("Room2")
TIMESLOT1 = Timeslot("MONDAY", time(12, 0), time(13, 0))
TIMESLOT2 = Timeslot("TUESDAY", time(12, 0), time(13, 0))
TIMESLOT3 = Timeslot("TUESDAY", time(13, 0), time(14, 0))
TIMESLOT4 = Timeslot("TUESDAY", time(15, 0), time(16, 0))

constraint_verifier = ConstraintVerifier.build(define_constraints, Timetable, Lesson)

def test_room_conflict():
    first_lesson = Lesson("1", "Subject1", "Teacher1", "Group1", TIMESLOT1, ROOM1)
    conflicting_lesson = Lesson("2", "Subject2", "Teacher2", "Group2", TIMESLOT1, ROOM1)
    non_conflicting_lesson = Lesson("3", "Subject3", "Teacher3", "Group3", TIMESLOT2, ROOM1)
    (constraint_verifier.verify_that(room_conflict)
        .given(first_lesson, conflicting_lesson, non_conflicting_lesson)
        .penalizes_by(1))
----
--
====

This test verifies that the constraint `TimetableConstraintProvider::roomConflict` penalizes with a match weight of `1`
when given three lessons in the same room, where two lessons have the same timeslot.
Therefore, a constraint weight of `10hard` would reduce the score by `-10hard`.

Notice how `ConstraintVerifier` ignores the constraint weight during testing - even
if those constraint weights are hard coded in the `ConstraintProvider` - because
constraints weights change regularly before going into production.
This way, constraint weight tweaking does not break the unit tests.

For more, see xref:constraints-and-score/score-calculation.adoc#constraintStreamsTesting[Testing Constraint Streams].

=== Logging

When adding constraints in your `ConstraintProvider`,
keep an eye on the _move evaluation speed_ in the `info` log,
after solving for the same amount of time, to assess the performance impact:

[source]
----
... Solving ended: ..., move evaluation speed (29455/sec), ...
----

To understand how Timefold Solver is solving your problem internally:

[tabs]
====
Python::
+
--
Change the logging in the `logging.conf` file:

[source,text]
----
[logger_timefold_solver]
level=DEBUG
qualname=timefold.solver
handlers=consoleHandler
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=simpleFormatter
args=(sys.stdout,)
----
--
====

Use `debug` logging to show every _step_:

[source,options="nowrap"]
----
... Solving started: time spent (67), best score (0hard/0soft), environment mode (PHASE_ASSERT), random (JDK with seed 0).
...     CH step (0), time spent (128), score (0hard/0soft), selected move count (15), picked move ([Math(101) {null -> Room A}, Math(101) {null -> MONDAY 08:30}]).
...     CH step (1), time spent (145), score (0hard/0soft), selected move count (15), picked move ([Physics(102) {null -> Room A}, Physics(102) {null -> MONDAY 09:30}]).
...
----

Use `trace` logging to show every _step_ and every _move_ per step.


=== Make a standalone application

In order to run the application outside an IDE easily, you will need to make some changes to the configuration of your build tool.

[tabs]
====
Python::
+
--

For Python, add the following to your `pyproject.toml`:

[source,toml,options="nowrap"]
----
[project.scripts]
run-app = "hello_world:main"
----

After installing the project,
`run-app` will be available as an executable that can be run from the command line:

[source,options="nowrap"]
----
$ pip install .
...
$ run-app
----
--
====


== Summary

Congratulations!
You have just developed a Python or application with https://timefold.ai[Timefold]!

If you ran into any issues, take a look at  {hello-world-python-quickstart-url}[the Python quickstart source code].
