[#backwardsCompatibility]
= Backwards compatibility
:doctype: book
:icons: font

[#previewFeatures]
== Preview features

Timefold Solver includes several components which are only available as preview features.
We use preview features as means of sharing our work with the community early
and to get feedback on how to develop them further,
without being hamstrung by our strict backwards compatibility guarantees.

We deliver preview features to the same standard of quality as the rest of Timefold Solver.
However, their APIs and behavior are not yet considered stable, pending user feedback.
Any class, method or field related to these features may change or be removed without prior notice,
although we strive to avoid this as much as possible.

Preview features need to be activated in the solverConfig.xml file.

[source,xml,options="nowrap"]
----
<solver xmlns="https://timefold.ai/xsd/solver">
  <enablePreviewFeature>DIVERSIFIED_LATE_ACCEPTANCE</enablePreviewFeature>
  <enablePreviewFeature>DECLARATIVE_SHADOW_VARIABLES</enablePreviewFeature>
  <enablePreviewFeature>PLANNING_SOLUTION_DIFF</enablePreviewFeature>
</solver>
----

Preview features often live in the `preview.api` package, and they are:

- xref:optimization-algorithms/local-search.adoc#diversifiedLateAcceptance[Diversified Late Acceptance] acceptor
in the `ai.timefold.solver.core.preview.api.domain.solution.diff` package,
and in the `SolutionManager`
- _Timefold Solver for Python_, which is currently in beta

We encourage you to try these preview features and give us feedback on your experience with them.
Please direct your feedback to
https://github.com/TimefoldAI/timefold-solver/discussions[Timefold Solver Github].
